language: python
python:
  - "3.8"

before_script: pip install -r requirements.txt

script:
  - python manage.py test
  
all_branches: true

deploy:
  provider: heroku
  api_key: 421f31cc-0c9b-4915-b26b-4d17ae816baf
  app: recipe-app-101
    # dev: node-hello-world-staging