language: python
python:
  - "3.8"

before_script: pip install -r requirements.txt

script:
  - python manage.py test


deploy:
  provider: heroku
  api_key: 421f31cc-0c9b-4915-b26b-4d17ae816baf
  app: recipe-app-101
  on:
    repo: khabdrick/django-travis-heroku
    branch: deploy
    # dev: node-hello-world-staging