language: python
python:
  - "3.10"

before_script: pip install -r requirements.txt

script:
  - python manage.py test

deploy:
  provider: heroku
  api_key:
    secure: "421f31cc-0c9b-4915-b26b-4d17ae816baf"

deploy:
  provider: heroku
  api_key: "421f31cc-0c9b-4915-b26b-4d17ae816baf"
  app: recipe-api-101